import { Product } from "@/modules/inventory/domain/entities/product.entity";
import type { ProductResponseDto } from "@/modules/inventory/application/dto/product.dto";

export class ProductMapper {
  static toDomain(dto: ProductResponseDto): Product {
    return Product.create({
      id: dto.id,
      sku: dto.sku,
      name: dto.name,
      description: typeof dto.description === "string" ? dto.description : null,
      categories: dto.categories ?? [],
      unitOfMeasure: dto.unitOfMeasure,
      cost: dto.cost,
      price: dto.price,
      minStock: dto.minStock ?? 0,
      maxStock: dto.maxStock ?? 0,
      isActive: dto.isActive,
      imageUrl: typeof dto.imageUrl === "string" ? dto.imageUrl : null,
      createdAt: new Date(dto.createdAt),
      updatedAt: new Date(dto.updatedAt),
      averageCost: dto.averageCost ?? 0,
      totalStock: dto.totalStock ?? 0,
      margin: dto.margin ?? 0,
      profit: dto.profit ?? 0,
      safetyStock: dto.safetyStock ?? 0,
      totalIn30d: dto.totalIn30d ?? 0,
      totalOut30d: dto.totalOut30d ?? 0,
      avgDailyConsumption: dto.avgDailyConsumption ?? 0,
      daysOfStock: dto.daysOfStock ?? null,
      turnoverRate: dto.turnoverRate ?? 0,
      lastMovementDate: dto.lastMovementDate ?? null,
      barcode: dto.barcode ?? null,
      statusChangedBy: dto.statusChangedBy ?? null,
      statusChangedAt: dto.statusChangedAt ?? null,
      companyId: dto.companyId ?? null,
      companyName: dto.companyName ?? null,
      brandId: dto.brandId ?? null,
      brandName: dto.brandName ?? null,
    });
  }

  static toDto(entity: Product): ProductResponseDto {
    return {
      id: entity.id,
      sku: entity.sku,
      name: entity.name,
      description: entity.description,
      categories: entity.categories,
      unitOfMeasure: entity.unitOfMeasure,
      cost: entity.cost,
      price: entity.price,
      minStock: entity.minStock,
      maxStock: entity.maxStock,
      isActive: entity.isActive,
      imageUrl: entity.imageUrl,
      createdAt: entity.createdAt.toISOString(),
      updatedAt: entity.updatedAt.toISOString(),
      averageCost: entity.averageCost,
      totalStock: entity.totalStock,
      margin: entity.margin,
      profit: entity.profit,
      safetyStock: entity.safetyStock,
      totalIn30d: entity.totalIn30d,
      totalOut30d: entity.totalOut30d,
      avgDailyConsumption: entity.avgDailyConsumption,
      daysOfStock: entity.daysOfStock,
      turnoverRate: entity.turnoverRate,
      lastMovementDate: entity.lastMovementDate,
      barcode: entity.barcode ?? null,
      statusChangedBy: entity.statusChangedBy ?? null,
      statusChangedAt: entity.statusChangedAt ?? null,
      companyId: entity.companyId ?? null,
      companyName: entity.companyName ?? null,
      brandId: entity.brandId ?? null,
      brandName: entity.brandName ?? null,
    };
  }
}
