// Permission constants - mirrors backend SYSTEM_PERMISSIONS
// Format: MODULE:ACTION

export const PERMISSIONS = {
  // Users
  USERS_CREATE: "USERS:CREATE",
  USERS_READ: "USERS:READ",
  USERS_UPDATE: "USERS:UPDATE",
  USERS_DELETE: "USERS:DELETE",
  USERS_MANAGE_ROLES: "USERS:MANAGE_ROLES",

  // Roles
  ROLES_CREATE: "ROLES:CREATE",
  ROLES_READ: "ROLES:READ",
  ROLES_UPDATE: "ROLES:UPDATE",
  ROLES_DELETE: "ROLES:DELETE",

  // Warehouses
  WAREHOUSES_CREATE: "WAREHOUSES:CREATE",
  WAREHOUSES_READ: "WAREHOUSES:READ",
  WAREHOUSES_UPDATE: "WAREHOUSES:UPDATE",
  WAREHOUSES_DELETE: "WAREHOUSES:DELETE",

  // Products
  PRODUCTS_CREATE: "PRODUCTS:CREATE",
  PRODUCTS_READ: "PRODUCTS:READ",
  PRODUCTS_UPDATE: "PRODUCTS:UPDATE",
  PRODUCTS_DELETE: "PRODUCTS:DELETE",
  PRODUCTS_IMPORT: "PRODUCTS:IMPORT",

  // Inventory
  INVENTORY_READ: "INVENTORY:READ",
  INVENTORY_ENTRY: "INVENTORY:ENTRY",
  INVENTORY_EXIT: "INVENTORY:EXIT",
  INVENTORY_TRANSFER: "INVENTORY:TRANSFER",
  INVENTORY_ADJUST: "INVENTORY:ADJUST",

  // Sales
  SALES_CREATE: "SALES:CREATE",
  SALES_READ: "SALES:READ",
  SALES_UPDATE: "SALES:UPDATE",
  SALES_DELETE: "SALES:DELETE",
  SALES_CONFIRM: "SALES:CONFIRM",
  SALES_CANCEL: "SALES:CANCEL",
  SALES_PICK: "SALES:PICK",
  SALES_SHIP: "SALES:SHIP",
  SALES_COMPLETE: "SALES:COMPLETE",
  SALES_RETURN: "SALES:RETURN",
  SALES_SWAP: "SALES:SWAP",

  // Returns
  RETURNS_CREATE: "RETURNS:CREATE",
  RETURNS_READ: "RETURNS:READ",
  RETURNS_UPDATE: "RETURNS:UPDATE",
  RETURNS_DELETE: "RETURNS:DELETE",
  RETURNS_CONFIRM: "RETURNS:CONFIRM",
  RETURNS_CANCEL: "RETURNS:CANCEL",

  // Reports
  REPORTS_READ: "REPORTS:READ",
  REPORTS_READ_SENSITIVE: "REPORTS:READ_SENSITIVE",
  REPORTS_EXPORT: "REPORTS:EXPORT",

  // Audit
  AUDIT_READ: "AUDIT:READ",
  AUDIT_EXPORT: "AUDIT:EXPORT",

  // Companies (Business Lines)
  COMPANIES_CREATE: "COMPANIES:CREATE",
  COMPANIES_READ: "COMPANIES:READ",
  COMPANIES_UPDATE: "COMPANIES:UPDATE",
  COMPANIES_DELETE: "COMPANIES:DELETE",

  // Settings
  SETTINGS_MANAGE: "SETTINGS:MANAGE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Map navigation routes to required permissions
export const ROUTE_PERMISSIONS: Record<string, Permission[]> = {
  "/dashboard": [], // Always accessible
  "/dashboard/inventory/products": [PERMISSIONS.PRODUCTS_READ],
  "/dashboard/inventory/categories": [PERMISSIONS.PRODUCTS_READ],
  "/dashboard/inventory/warehouses": [PERMISSIONS.WAREHOUSES_READ],
  "/dashboard/inventory/movements": [PERMISSIONS.INVENTORY_READ],
  "/dashboard/inventory/transfers": [PERMISSIONS.INVENTORY_TRANSFER],
  "/dashboard/inventory/stock": [PERMISSIONS.INVENTORY_READ],
  "/dashboard/sales": [PERMISSIONS.SALES_READ],
  "/dashboard/returns": [PERMISSIONS.RETURNS_READ],
  "/dashboard/reports": [PERMISSIONS.REPORTS_READ],
  "/dashboard/imports": [PERMISSIONS.PRODUCTS_IMPORT],
  "/dashboard/users": [PERMISSIONS.USERS_READ],
  "/dashboard/roles": [PERMISSIONS.ROLES_READ],
  "/dashboard/audit": [PERMISSIONS.AUDIT_READ],
  "/dashboard/inventory/companies": [PERMISSIONS.COMPANIES_READ],
  "/dashboard/settings": [], // Always accessible
};
